/**
 * Memes, curiosidades e nostalgia SOBRE MÍDIA (F-163). Todo item traz `foto`: termo de busca em inglês para a foto que
 * combina com a cena (o meme "Quando o Wi-Fi cai…" aparece sobre uma pessoa desesperada com o notebook, e assim por diante).
 * Curiosidades: só fatos amplamente documentados. Tudo para toda a família e próprio para comércio.
 */

/** { t: legenda, foto } */
export const MEMES = [
  { t: 'Quando você diz “só mais 5 minutinhos” e acorda uma hora depois.', foto: 'sleepy person alarm clock bed' },
  { t: 'Quando o Wi-Fi cai e você descobre que tem família.', foto: 'family dinner phones' },
  { t: 'Segunda-feira chegando como se alguém tivesse pedido.', foto: 'tired worker monday morning' },
  { t: 'Quando a comida chega e todo mundo vira fotógrafo profissional.', foto: 'taking photo of food restaurant' },
  { t: 'Eu: este mês vou economizar. Também eu: “mas está em promoção!”', foto: 'shopping bags sale' },
  { t: 'Quando você procura o celular… falando no celular.', foto: 'confused woman holding smartphone' },
  { t: 'A dieta começa segunda. Qual segunda? Ninguém sabe.', foto: 'salad and burger choice' },
  { t: 'Quando o boleto chega antes do salário.', foto: 'worried man bills' },
  { t: 'Abrindo a geladeira pela décima vez esperando aparecer algo novo.', foto: 'person looking inside open fridge' },
  { t: 'Quando alguém diz “vou ser rápido” e fala por 40 minutos.', foto: 'person talking a lot meeting bored' },
  { t: 'Sexta-feira: o dia oficial do “agora vai”.', foto: 'happy friday office celebration' },
  { t: 'Quando o motorista diz que já está chegando e ainda faltam 12 minutos.', foto: 'waiting for ride on street' },
  { t: 'Carregador em 1%: a maior aventura do dia.', foto: 'low battery phone' },
  { t: 'Quando você vai à academia só para fazer o check-in.', foto: 'gym selfie' },
  { t: 'Quando a mãe diz: “temos comida em casa”.', foto: 'empty plate kitchen disappointed' },
  { t: 'Quando você decora a senha e o site pede para trocar.', foto: 'frustrated man password laptop' },
  { t: 'O fim de semana passa em 5 minutos. A segunda dura 3 dias.', foto: 'weekend relax sofa' },
  { t: 'Quando a música boa começa bem na hora de sair do carro.', foto: 'singing in the car' },
  { t: 'Eu tentando dobrar lençol de elástico.', foto: 'folding bed sheet struggling' },
  { t: 'Quando o pão de queijo sai do forno.', foto: 'cheese bread fresh from oven' },
  { t: 'Quando você acha dinheiro esquecido no bolso da calça.', foto: 'surprised man holding money' },
  { t: 'Quando o chefe diz: “pode ir mais cedo hoje”.', foto: 'happy employee leaving office' },
  { t: 'Esperando o micro-ondas chegar no zero como se fosse Réveillon.', foto: 'waiting microwave countdown' },
  { t: 'A previsão diz sol, você sai sem guarda-chuva… e chove.', foto: 'person caught in rain' },
  { t: 'Quando a série termina e você não sabe mais o que fazer da vida.', foto: 'watching tv binge sofa' },
  { t: 'Lembrar de uma vergonha de 2009 às 3 da manhã.', foto: 'insomnia night bed thinking' },
  { t: 'Quando você entra no cômodo e esquece o que foi buscar.', foto: 'confused person standing in room' },
  { t: 'Quando o cartão passa na primeira tentativa.', foto: 'paying with credit card happy' },
  { t: 'Quando falta 1 real e você acha uma moeda no fundo da bolsa.', foto: 'coins in a purse' },
  { t: 'Quando você pede “sem cebola” e vem com cebola.', foto: 'burger with onions disappointed' },
  { t: 'Quando o ônibus passa bem na hora que você chega no ponto.', foto: 'missing the bus' },
  { t: 'Quando a fila do lado sempre anda mais rápido.', foto: 'long supermarket queue' },
  { t: 'Quando você ensaia a conversa no banho e na hora esquece tudo.', foto: 'singing in the shower' },
  { t: 'Quando o GPS diz “recalculando rota” pela quinta vez.', foto: 'lost driver gps car' },
  { t: 'Quando você acorda um minuto antes do despertador.', foto: 'person waking up before alarm' },
  { t: 'Quando a água do chuveiro fica gelada no meio do banho.', foto: 'cold shower shock' },
  { t: 'Quando alguém come a última fatia de pizza que você estava guardando.', foto: 'last slice of pizza' },
  { t: 'Quando você acha que é sexta… e ainda é quarta.', foto: 'disappointed man calendar' },
  { t: 'Quando o áudio no zap tem 7 minutos.', foto: 'long voice message smartphone' },
  { t: 'Quando você puxa a porta e era para empurrar.', foto: 'glass door push pull' },
  { t: 'Quando você lava o carro e começa a chover.', foto: 'washing car rain' },
  { t: 'Quando você ri da própria piada antes de terminar de contar.', foto: 'laughing woman' },
  { t: 'Quando o pedido do delivery “saiu para entrega”.', foto: 'delivery motorcycle courier' },
  { t: 'Quando você diz “vou só dar uma olhadinha” na loja.', foto: 'shopping mall bags' },
  { t: 'Quando o controle remoto some… e estava no seu colo.', foto: 'tv remote control sofa' },
  { t: 'Quando você arruma o cabelo e começa a ventar.', foto: 'windy hair woman' },
  { t: 'Quando a sobremesa é melhor que o almoço.', foto: 'chocolate dessert' },
  { t: 'Quando você tira a foto perfeita… com o olho fechado.', foto: 'funny selfie' },
  { t: 'Quando o café acaba e ainda é segunda-feira.', foto: 'empty coffee cup tired' },
  { t: 'Quando o salário cai e vai embora no mesmo dia.', foto: 'wallet empty' },
  { t: 'Quando você promete dormir cedo e às 2h ainda está no celular.', foto: 'phone in bed at night' },
  { t: 'Quando a pessoa na sua frente na fila tem 47 itens.', foto: 'full shopping cart' },
  { t: 'Quando você sai de casa e volta para ver se trancou a porta.', foto: 'locking front door' },
  { t: 'Quando a playlist aleatória toca exatamente a música que você queria.', foto: 'headphones happy music' },
  { t: 'Quando o elevador para em todos os andares.', foto: 'elevator buttons' },
  { t: 'Quando você decide cozinhar e a louça te olha de volta.', foto: 'sink full of dishes' },
  { t: 'Quando você acha uma batata frita perdida no fundo do saquinho.', foto: 'french fries' },
  { t: 'Quando o cachorro te olha como se entendesse tudo.', foto: 'dog looking at camera' },
  { t: 'Quando a conta do restaurante chega e todo mundo fica quieto.', foto: 'restaurant bill friends' },
  { t: 'Quando você lembra que amanhã é feriado.', foto: 'happy people celebrating' },
  { t: 'Quando você pisa numa peça de brinquedo no escuro.', foto: 'toy bricks on floor' },
  { t: 'Quando você passa protetor solar e esquece a orelha.', foto: 'sunscreen beach' },
  { t: 'Quando o time faz gol aos 49 do segundo tempo.', foto: 'fans celebrating goal stadium' },
  { t: 'Quando você começa uma série para ver “só um episódio”.', foto: 'sofa blanket popcorn tv' },
  { t: 'Quando a vó pergunta se você já comeu… pela terceira vez.', foto: 'grandmother serving food' },
  { t: 'Quando a impressora funciona de primeira.', foto: 'printer office happy' },
  { t: 'Quando o frio chega e o cobertor vira seu melhor amigo.', foto: 'cozy blanket winter coffee' },
  { t: 'Quando você abre o pacote de biscoito e ele está todo quebrado.', foto: 'broken cookies' },
  { t: 'Quando você salva o arquivo um segundo antes do computador travar.', foto: 'relieved man laptop' },
  { t: 'Quando a chuva para bem na hora que você chega em casa.', foto: 'rainbow after rain' },
  { t: 'Quando você encontra vaga para estacionar bem na porta.', foto: 'parking spot car' },
  { t: 'Quando o bolo sai do forno e o cheiro invade a casa.', foto: 'fresh baked cake' },
  { t: 'Quando o despertador toca e o cobertor puxa você de volta.', foto: 'person sleeping under blanket' },
  { t: 'Quando alguém diz “tenho uma má notícia e uma boa” e você escolhe a boa primeiro.', foto: 'surprised woman looking' },
  { t: 'Quando o garçom diz “bom apetite” e você responde “para você também”.', foto: 'waiter restaurant table' },
  { t: 'Eu olhando o saldo antes de olhar o cardápio.', foto: 'restaurant menu' },
  { t: 'Quando o pastel chega e você descobre que é de vento.', foto: 'pastel fried snack' },
  { t: 'Quando a pessoa fala “depois a gente se fala” e nunca mais fala.', foto: 'two friends coffee talking' },
  { t: 'Quando você diz “vamos marcar” e os dois sabem que não vai acontecer.', foto: 'friends meeting cafe' },
  { t: 'Quando a pipoca do micro-ondas queima e a casa inteira sabe.', foto: 'burnt popcorn microwave' },
  { t: 'Quando o chinelo some e a casa vira cena de investigação.', foto: 'flip flops sandals' },
  { t: 'Quando o ar-condicionado é o único amigo de verdade no verão.', foto: 'air conditioner cooling summer' },
  { t: 'Quando você abre o armário e todas as roupas dizem “não tem nada para vestir”.', foto: 'woman choosing clothes closet' },
  { t: 'Quando a bateria do celular cai de 20% para 1% em um minuto.', foto: 'smartphone battery' },
  { t: 'Quando o vizinho resolve furar a parede no domingo de manhã.', foto: 'drilling wall' },
];

/** { t: fato, foto } — só fatos consolidados. */
export const CURIOSIDADES = [
  { t: 'O polvo tem três corações e sangue azul.', foto: 'octopus underwater' },
  { t: 'O mel pode durar milhares de anos: já foi encontrado mel ainda comestível em tumbas do Egito antigo.', foto: 'honey jar' },
  { t: 'Os coalas dormem até 20 horas por dia.', foto: 'koala sleeping' },
  { t: 'Em Vênus, um dia dura mais do que um ano.', foto: 'planet venus' },
  { t: 'A Torre Eiffel pode ficar até 15 centímetros mais alta no verão, por causa da dilatação do ferro.', foto: 'eiffel tower' },
  { t: 'As lontras-marinhas dormem de mãos dadas para não se afastarem umas das outras.', foto: 'sea otters' },
  { t: 'O coração humano bate cerca de 100 mil vezes por dia.', foto: 'heart beat stethoscope' },
  { t: 'Os tubarões existem há mais tempo do que as árvores.', foto: 'shark underwater' },
  { t: 'O Rio Amazonas leva ao oceano cerca de 20% de toda a água doce que os rios do mundo despejam no mar.', foto: 'amazon river aerial' },
  { t: 'Os flamingos são cor-de-rosa por causa dos pigmentos dos crustáceos e das algas que comem.', foto: 'pink flamingos' },
  { t: 'O beija-flor é capaz de voar para trás.', foto: 'hummingbird flying' },
  { t: 'Um raio é cerca de cinco vezes mais quente do que a superfície do Sol.', foto: 'lightning storm' },
  { t: 'A girafa tem sete vértebras no pescoço — o mesmo número que o ser humano.', foto: 'giraffe' },
  { t: 'A banana é levemente radioativa, por causa do potássio natural da fruta.', foto: 'bananas' },
  { t: 'A Grande Muralha da China não pode ser vista a olho nu da Lua.', foto: 'great wall of china' },
  { t: 'A estrela-do-mar não tem cérebro.', foto: 'starfish' },
  { t: 'O olho do avestruz é maior do que o próprio cérebro.', foto: 'ostrich' },
  { t: 'Os golfinhos dormem com metade do cérebro de cada vez.', foto: 'dolphin jumping' },
  { t: 'O Cristo Redentor é atingido por raios várias vezes por ano.', foto: 'christ the redeemer rio' },
  { t: 'A Lua se afasta da Terra cerca de 3,8 centímetros por ano.', foto: 'moon over earth' },
  { t: 'O corpo humano adulto tem 206 ossos.', foto: 'human skeleton model' },
  { t: 'O Oceano Pacífico é maior do que todos os continentes juntos.', foto: 'pacific ocean aerial' },
  { t: 'As águas-vivas existem há mais de 500 milhões de anos.', foto: 'jellyfish' },
  { t: 'O guepardo vai de 0 a 100 km/h em cerca de 3 segundos.', foto: 'cheetah running' },
  { t: 'O pinguim-imperador consegue mergulhar a mais de 500 metros de profundidade.', foto: 'emperor penguin' },
  { t: 'O Brasil é o maior produtor de café do mundo.', foto: 'coffee plantation beans' },
  { t: 'O Pantanal é a maior planície alagável do planeta.', foto: 'pantanal wetlands' },
  { t: 'As Cataratas do Iguaçu têm cerca de 275 quedas-d’água.', foto: 'iguazu falls' },
  { t: 'O Sol concentra cerca de 99,8% de toda a massa do Sistema Solar.', foto: 'sun solar flare' },
  { t: 'A luz do Sol leva cerca de 8 minutos para chegar à Terra.', foto: 'sunrise over earth' },
  { t: 'As unhas das mãos crescem mais rápido do que as dos pés.', foto: 'hands nails' },
  { t: 'A baleia-azul é o maior animal que já existiu na Terra.', foto: 'blue whale' },
  { t: 'A água cobre cerca de 71% da superfície da Terra.', foto: 'earth from space blue' },
  { t: 'O Everest é a montanha mais alta do mundo, com cerca de 8.849 metros.', foto: 'mount everest' },
  { t: 'O Rio Amazonas é o maior rio do mundo em volume de água.', foto: 'amazon river boat' },
  { t: 'A Floresta Amazônica é a maior floresta tropical do planeta.', foto: 'amazon rainforest' },
  { t: 'No cavalo-marinho, é o macho quem carrega os filhotes.', foto: 'seahorse' },
  { t: 'As formigas não têm pulmões: respiram por pequenos orifícios no corpo.', foto: 'ants macro' },
  { t: 'O camaleão muda de cor principalmente para regular a temperatura e se comunicar.', foto: 'chameleon' },
  { t: 'O avestruz é a maior ave do mundo.', foto: 'ostrich head' },
  { t: 'O beija-flor pode bater as asas até 80 vezes por segundo.', foto: 'hummingbird flower' },
  { t: 'A preguiça pode levar até um mês para digerir uma refeição.', foto: 'sloth' },
  { t: 'A coruja não mexe os olhos: por isso gira a cabeça até cerca de 270 graus.', foto: 'owl' },
  { t: 'O elefante é o maior animal terrestre do planeta.', foto: 'elephant savanna' },
  { t: 'Os morcegos são os únicos mamíferos capazes de voar de verdade.', foto: 'bat flying' },
  { t: 'O tubarão-baleia é o maior peixe do mundo.', foto: 'whale shark' },
  { t: 'Júpiter é o maior planeta do Sistema Solar.', foto: 'planet jupiter' },
  { t: 'Saturno é tão pouco denso que, em teoria, flutuaria na água.', foto: 'planet saturn rings' },
  { t: 'Marte é vermelho por causa do óxido de ferro — a ferrugem — da sua superfície.', foto: 'planet mars' },
  { t: 'A Estação Espacial Internacional dá uma volta na Terra a cada cerca de 90 minutos.', foto: 'international space station' },
  { t: 'O fêmur, osso da coxa, é o osso mais forte do corpo humano.', foto: 'anatomy bones' },
  { t: 'O menor osso do corpo humano fica no ouvido e se chama estribo.', foto: 'human ear' },
  { t: 'A pele é o maior órgão do corpo humano.', foto: 'skin close up' },
  { t: 'Passamos cerca de um terço da vida dormindo.', foto: 'sleeping peacefully' },
  { t: 'O som viaja cerca de quatro vezes mais rápido na água do que no ar.', foto: 'underwater diver' },
  { t: 'O diamante é o material natural mais duro da Terra.', foto: 'diamond' },
  { t: 'O Brasil tem 26 estados e o Distrito Federal.', foto: 'brazil flag' },
  { t: 'Brasília foi inaugurada em 21 de abril de 1960.', foto: 'brasilia national congress' },
  { t: 'O Maracanã foi inaugurado para a Copa do Mundo de 1950.', foto: 'maracana stadium' },
  { t: 'O Brasil é o único país pentacampeão mundial de futebol.', foto: 'soccer world cup trophy' },
  { t: 'O português é a língua oficial de nove países.', foto: 'world map languages' },
  { t: 'O açaí é um fruto nativo da Amazônia.', foto: 'acai bowl' },
  { t: 'O Brasil é o maior produtor de laranja do mundo.', foto: 'oranges' },
  { t: 'O chocolate é feito a partir das sementes do cacau.', foto: 'cocoa pods' },
  { t: 'O pão de queijo é um dos símbolos da culinária de Minas Gerais.', foto: 'cheese bread' },
  { t: 'Os girassóis jovens acompanham o movimento do Sol ao longo do dia.', foto: 'sunflower field' },
  { t: 'O bambu está entre as plantas que crescem mais rápido no mundo.', foto: 'bamboo forest' },
  { t: 'A Estátua da Liberdade foi um presente da França aos Estados Unidos.', foto: 'statue of liberty' },
  { t: 'O Monte Roraima fica na fronteira entre Brasil, Venezuela e Guiana.', foto: 'mount roraima' },
  { t: 'O Rio São Francisco é carinhosamente chamado de “Velho Chico”.', foto: 'sao francisco river' },
  { t: 'Nos Lençóis Maranhenses, lagoas de água doce se formam entre as dunas na época das chuvas.', foto: 'lencois maranhenses' },
  { t: 'Fernando de Noronha é um arquipélago formado por 21 ilhas.', foto: 'fernando de noronha beach' },
  { t: 'A Chapada Diamantina, na Bahia, recebeu esse nome por causa do garimpo de diamantes.', foto: 'chapada diamantina' },
  { t: 'Uma pessoa pisca, em média, de 15 a 20 vezes por minuto.', foto: 'eye close up blinking' },
  { t: 'O cabelo cresce, em média, cerca de 1 centímetro por mês.', foto: 'long hair woman' },
  { t: 'Ao nível do mar, a água ferve a 100 °C.', foto: 'boiling water pot' },
  { t: 'A Torre de Pisa é inclinada por causa do solo mole em que foi construída.', foto: 'leaning tower of pisa' },
  { t: 'O café chegou ao Brasil em 1727, pelo Pará.', foto: 'coffee beans' },
  { t: 'A mandioca é uma planta originária da América do Sul.', foto: 'cassava roots' },
  { t: 'O Brasil é o quinto maior país do mundo em área.', foto: 'brazil aerial landscape' },
  { t: 'A Terra leva 365 dias e cerca de 6 horas para dar a volta no Sol — por isso existe o ano bissexto.', foto: 'earth sun orbit' },
  { t: 'Os gatos passam cerca de dois terços da vida dormindo.', foto: 'cat sleeping' },
  { t: 'A zebra tem listras únicas, como as impressões digitais das pessoas.', foto: 'zebra herd' },
];

/** { t: título, s: frase, foto } */
export const NOSTALGIA = [
  { t: 'Fita K7 e a caneta para rebobinar', s: 'Quem nunca salvou a fita com uma caneta?', foto: 'cassette tape' },
  { t: 'Locadora de vídeo', s: '“Seja gentil, rebobine a fita antes de devolver.”', foto: 'vhs video tapes' },
  { t: 'Sessão da Tarde', s: 'Depois da escola, filme garantido na TV.', foto: 'old television set' },
  { t: 'Antena de TV com esponja de aço', s: 'Um ajuste aqui, outro ali… e a imagem voltava!', foto: 'tv antenna roof' },
  { t: 'Orelhão e cartão telefônico', s: 'E a coleção de cartões, quem tinha?', foto: 'public payphone' },
  { t: 'Álbum de figurinhas da Copa', s: 'Trocar repetida no recreio era um evento.', foto: 'sticker album collection' },
  { t: 'Internet discada', s: 'Aquele barulhinho da conexão… e só depois da meia-noite!', foto: 'old desktop computer' },
  { t: 'Tamagotchi', s: 'O bichinho virtual que precisava de cuidado o dia inteiro.', foto: 'retro handheld toy' },
  { t: 'Celular tijolão e o jogo da cobrinha', s: 'A bateria durava uma semana!', foto: 'old mobile phone' },
  { t: 'Mensagem de texto contando caracteres', s: 'Cada torpedo tinha que caber em 160 letras.', foto: 'old nokia phone texting' },
  { t: 'Gravar música do rádio na fita', s: 'Torcendo para o locutor não falar por cima.', foto: 'vintage radio' },
  { t: 'Disquete', s: 'O ícone de “salvar” veio dele.', foto: 'floppy disk' },
  { t: 'Walkman', s: 'Música no bolso — e pilha de reserva na mochila.', foto: 'walkman cassette player headphones' },
  { t: 'Discman', s: 'Andar devagarinho para o CD não pular.', foto: 'compact disc' },
  { t: 'Máquina fotográfica de filme', s: '36 poses e a surpresa só na revelação.', foto: 'film camera' },
  { t: 'Caderno de perguntas', s: 'Nome, idade, cor preferida e “quem você ama?”', foto: 'notebook handwriting pen' },
  { t: 'Papel de carta', s: 'Colecionar, trocar… e nunca usar os mais bonitos.', foto: 'letter writing paper envelope' },
  { t: 'Ioiô, pião e bolinha de gude', s: 'As brincadeiras que enchiam a rua.', foto: 'marbles' },
  { t: 'Telefone de disco', s: 'Discar um número demorava — e ninguém reclamava.', foto: 'rotary dial telephone' },
  { t: 'Agenda telefônica de papel', s: 'Os números importantes a gente sabia de cor.', foto: 'address book' },
  { t: 'TV de tubo', s: 'Pesada, funda… e durava para sempre.', foto: 'crt television vintage' },
  { t: 'Vinil na vitrola', s: 'Lado A, lado B e a capa como obra de arte.', foto: 'vinyl record player' },
  { t: 'Guaraná em garrafa de vidro', s: 'E o casco retornável para trocar na venda.', foto: 'glass bottles vintage' },
  { t: 'Brincar na rua até escurecer', s: 'Pique-esconde, amarelinha e pega-pega.', foto: 'children playing in the street' },
  { t: 'Novela com a família reunida', s: 'Todo mundo na sala, na mesma hora.', foto: 'family watching tv living room' },
  { t: 'Assoprar o cartucho do videogame', s: 'Se não funcionava, era só assoprar e tentar de novo.', foto: 'retro video game console' },
  { t: 'Controle remoto com fita adesiva', s: 'Segurando as pilhas no lugar há anos.', foto: 'tv remote control' },
  { t: 'Gibi da banca de jornal', s: 'Ler e reler até a capa soltar.', foto: 'comic books' },
  { t: 'Pirulito com apito', s: 'Doce e barulho garantidos.', foto: 'lollipops' },
  { t: 'Caneta de dez cores', s: 'Apertar duas cores ao mesmo tempo era um desafio.', foto: 'colorful pens' },
  { t: 'Estojo de dois andares', s: 'O objeto mais cobiçado da sala.', foto: 'pencil case school supplies' },
  { t: 'Diário com cadeado', s: 'E a chavinha sempre sumia.', foto: 'diary with lock' },
  { t: 'Bambolê', s: 'Horas girando no quintal.', foto: 'hula hoop' },
  { t: 'Pular corda e elástico', s: 'Com música e tudo!', foto: 'jump rope children' },
  { t: 'Patins de quatro rodas', s: 'Os joelhos que o digam.', foto: 'roller skates' },
  { t: 'Carrinho de rolimã', s: 'A ladeira era a pista oficial.', foto: 'wooden go kart' },
  { t: 'Soltar pipa no fim da tarde', s: 'O céu cheio de cores.', foto: 'kites sky' },
  { t: 'Pega-varetas', s: 'Sem mexer nenhuma das outras!', foto: 'pick up sticks game' },
  { t: 'Jogo de botão', s: 'Campeonatos inteiros em cima da mesa.', foto: 'table football game' },
  { t: 'Dominó com os avós', s: 'Na varanda, depois do almoço de domingo.', foto: 'dominoes game' },
  { t: 'Quebra-cabeça de mil peças', s: 'E sempre faltava uma.', foto: 'jigsaw puzzle' },
  { t: 'Programar o videocassete', s: 'Para gravar a novela sem perder o capítulo.', foto: 'vcr video cassette recorder' },
  { t: 'Radinho de pilha no estádio', s: 'Ver o jogo e ouvir a narração ao mesmo tempo.', foto: 'portable radio' },
  { t: 'Cartão-postal', s: 'Chegava depois de você voltar da viagem.', foto: 'postcards' },
  { t: 'Lista telefônica', s: 'O livro mais grosso da casa.', foto: 'phone book' },
  { t: 'Fliperama da esquina', s: 'Uma ficha e muita habilidade.', foto: 'arcade machines' },
  { t: 'Totó no bar da esquina', s: 'Valia campeonato entre os amigos.', foto: 'foosball table' },
  { t: 'Sonho de padaria', s: 'Recheado e com açúcar por cima.', foto: 'doughnut cream' },
  { t: 'Picolé depois da aula', s: 'O melhor prêmio do dia.', foto: 'popsicle' },
  { t: 'Máquina de escrever', s: 'E o corretivo para cada errinho.', foto: 'typewriter' },
  { t: 'Jogar bola na rua', s: 'Parar a partida quando passava um carro.', foto: 'kids playing soccer street' },
  { t: 'Bicicleta com cestinha', s: 'Ir à padaria era uma aventura.', foto: 'vintage bicycle basket' },
  { t: 'Chamada de longa distância', s: 'Falar rápido porque a ligação era cara.', foto: 'old telephone call' },
  { t: 'Esperar a foto revelar', s: 'Uma semana de ansiedade.', foto: 'photo prints developing' },
  { t: 'Relógio de pulso digital', s: 'Aquele apitinho que marcava a hora cheia.', foto: 'digital wristwatch retro' },
  { t: 'Maria-fumaça e estações antigas', s: 'Viagem lenta, janelas abertas e muita conversa.', foto: 'steam train' },
  { t: 'Rádio na cozinha', s: 'O programa preferido tocando enquanto o café passava.', foto: 'old radio kitchen' },
  { t: 'Cinema de rua', s: 'A fila na porta e o cartaz pintado à mão.', foto: 'vintage cinema marquee' },
];
