/**
 * Bancos de conteúdo PRÓPRIO SOBRE MÍDIA (F-95) — decisão do proprietário: Memes/Humor sem imagens de terceiros.
 * Textos curtos, para toda a família, próprios para comércio. Curiosidades: só fatos amplamente documentados.
 * A cada 3 dias entra um trecho diferente de cada banco (rodízio em arte-base.mjs `daSemana`/`periodoDe3Dias`).
 * Ampliação em bancos-ampliacao.mjs (F-96).
 */
import { MAIS_CHARADAS, MAIS_PIADAS, MAIS_MEMES, MAIS_CURIOSIDADES, MAIS_NOSTALGIA } from './bancos-ampliacao.mjs';
export const CHARADAS = [
  ['Quanto mais se tira, maior fica?', 'O buraco'],
  ['Tem dentes, mas não morde?', 'O pente'],
  ['Cai em pé e corre deitada?', 'A chuva'],
  ['Tem cabeça e tem dente, não é bicho nem é gente?', 'O alho'],
  ['Quanto mais seca, mais molhada fica?', 'A toalha'],
  ['Passa diante do sol e não faz sombra?', 'O vento'],
  ['Tem pescoço, mas não tem cabeça?', 'A garrafa'],
  ['Tem olho, mas não enxerga?', 'A agulha'],
  ['Sobe quando a chuva desce?', 'O guarda-chuva'],
  ['Tem coroa, mas não é rei; tem escamas, mas não é peixe?', 'O abacaxi'],
  ['É seu, mas os outros usam mais do que você?', 'O seu nome'],
  ['Tem asa, mas não voa; tem bico, mas não bica?', 'O bule'],
  ['Nasce grande e morre pequeno?', 'O lápis'],
  ['Tem cidades, mas não tem casas; tem rios, mas não tem água?', 'O mapa'],
  ['Viaja o mundo inteiro sem sair do cantinho?', 'O selo'],
  ['Está no meio do começo, no começo do meio e no fim do fim?', 'A letra M'],
  ['Está sempre à sua frente, mas você não consegue ver?', 'O futuro'],
  ['Quebra quando você diz o nome dele?', 'O silêncio'],
  ['Tem pernas, mas não anda?', 'A mesa'],
  ['Dá muitas voltas e não sai do lugar?', 'O relógio'],
  ['É feita para andar e não anda?', 'A rua'],
  ['Tem boca, mas não fala; tem leito, mas não dorme?', 'O rio'],
  ['Pesa pouco, mas nem o mais forte segura por muito tempo?', 'A respiração'],
  ['Quanto mais se lava, mais suja fica?', 'A água'],
  ['Tem capa, mas não é super-herói; tem folhas, mas não é árvore?', 'O livro'],
  ['Tem teclas, mas não abre nenhuma porta?', 'O piano'],
  ['Anda com os pés na cabeça?', 'O piolho'],
  ['Tem casca, tem clara e tem gema, mas não é joia?', 'O ovo'],
  ['Corre a casa inteira e depois fica no cantinho?', 'A vassoura'],
  ['Tem barba, mas não é homem; tem dente, mas não é gente?', 'O milho'],
];

export const PIADAS = [
  ['Por que o livro de matemática ficou triste?', 'Porque tinha muitos problemas.'],
  ['O que o zero disse para o oito?', 'Que cinto bonito!'],
  ['Por que a plantinha não foi atendida no hospital?', 'Porque só tinha médico de plantão.'],
  ['Qual é o doce preferido do átomo?', 'Pé-de-molécula.'],
  ['Como o elétron atende o telefone?', 'Próton!'],
  ['O que é um pontinho amarelo no céu?', 'Um yellowcóptero.'],
  ['O que a vaca foi fazer no espaço?', 'Procurar a Via Láctea.'],
  ['Qual é o animal mais antigo?', 'A zebra, porque é em preto e branco.'],
  ['O que o tomate foi fazer no banco?', 'Tirar extrato.'],
  ['Qual é a fruta que anda de trem?', 'O kiwiuiui.'],
  ['O que o cavalo foi fazer no orelhão?', 'Passar um trote.'],
  ['Qual é o contrário de volátil?', 'Vem cá, sobrinho.'],
  ['O que o café disse para o açúcar?', 'Sem você, a minha vida é amarga.'],
  ['Qual é o peixe que caiu do décimo andar?', 'Aaaaaaatum!'],
  ['Qual é o rei dos queijos?', 'O reiqueijão.'],
  ['Por que o computador foi preso?', 'Porque executou um programa.'],
  ['O que o lápis disse para o apontador?', 'Deixa de rodeio e vai direto ao ponto.'],
  ['Qual é a cidade brasileira que não tem táxi?', 'Uberlândia.'],
  ['Por que o pinheiro não se perde na floresta?', 'Porque ele tem um mapinha.'],
  ['O que o pato disse para a pata?', 'Vem quá!'],
  ['Por que o celular foi ao psicólogo?', 'Porque perdeu o contato com a realidade.'],
  ['O que a impressora disse para a outra?', 'Essa folha é sua ou é impressão minha?'],
  ['O que um ponteiro do relógio disse para o outro?', 'Nos vemos daqui a uma hora!'],
  ['Por que a galinha atravessou a rua?', 'Para chegar do outro lado.'],
  ['O que o pagodeiro foi fazer na igreja?', 'Cantar pá God.'],
  ['Qual é a comida preferida do Wi-Fi?', 'Rede-limão.'],
];

export const MEMES = [
  'Quando você diz "só mais 5 minutinhos" e acorda uma hora depois.',
  'Quando o Wi-Fi cai e você descobre que tem família.',
  'Segunda-feira chegando como se alguém tivesse pedido.',
  'Quando a comida chega e todo mundo vira fotógrafo profissional.',
  'Eu: este mês vou economizar. Também eu: "mas está em promoção!"',
  'Quando você procura o celular… falando no celular.',
  'A dieta começa segunda. Qual segunda? Ninguém sabe.',
  'Quando o boleto chega antes do salário.',
  'Abrindo a geladeira pela décima vez esperando aparecer algo novo.',
  'Quando alguém diz "vou ser rápido" e fala por 40 minutos.',
  'Sexta-feira: o dia oficial do "agora vai".',
  'Quando o motorista diz que já está chegando e ainda faltam 12 minutos.',
  'Carregador em 1%: a maior aventura do dia.',
  'Quando você vai à academia só para fazer o check-in.',
  'Quando a mãe diz: "temos comida em casa".',
  'Quando você decora a senha e o site pede para trocar.',
  'O fim de semana passa em 5 minutos. A segunda dura 3 dias.',
  'Quando a música boa começa bem na hora de sair do carro.',
  'Eu tentando dobrar lençol de elástico.',
  'Quando você diz "tchau" e sai andando para o mesmo lado da pessoa.',
  'Quando o pão de queijo sai do forno.',
  'Quando você acha dinheiro esquecido no bolso da calça.',
  'Quando o chefe diz: "pode ir mais cedo hoje".',
  'Esperando o micro-ondas chegar no zero como se fosse Réveillon.',
  'A previsão diz sol, você sai sem guarda-chuva… e chove.',
  'Quando a série termina e você não sabe mais o que fazer da vida.',
  'Lembrar de uma vergonha de 2009 às 3 da manhã.',
  'Quando você entra no cômodo e esquece o que foi buscar.',
  'Quando o cartão passa na primeira tentativa.',
  'Quando falta 1 real e você acha uma moeda no fundo da bolsa.',
];

export const CURIOSIDADES = [
  'O polvo tem três corações e sangue azul.',
  'O mel pode durar milhares de anos: já foi encontrado mel ainda comestível em tumbas do Egito antigo.',
  'Os coalas dormem até 20 horas por dia.',
  'Em Vênus, um dia dura mais do que um ano.',
  'A Torre Eiffel pode ficar até 15 centímetros mais alta no verão, por causa da dilatação do ferro.',
  'As lontras-marinhas dormem de mãos dadas para não se afastarem umas das outras.',
  'O coração humano bate cerca de 100 mil vezes por dia.',
  'Os tubarões existem há mais tempo do que as árvores.',
  'O Rio Amazonas leva ao oceano cerca de 20% de toda a água doce que os rios do mundo despejam no mar.',
  'Os flamingos são cor-de-rosa por causa dos pigmentos dos crustáceos e das algas que comem.',
  'O beija-flor é capaz de voar para trás.',
  'Um raio é cerca de cinco vezes mais quente do que a superfície do Sol.',
  'A girafa tem sete vértebras no pescoço — o mesmo número que o ser humano.',
  'A banana é levemente radioativa, por causa do potássio natural da fruta.',
  'A Grande Muralha da China não pode ser vista a olho nu da Lua.',
  'A estrela-do-mar não tem cérebro.',
  'O olho do avestruz é maior do que o próprio cérebro.',
  'Os golfinhos dormem com metade do cérebro de cada vez.',
  'O Cristo Redentor é atingido por raios várias vezes por ano.',
  'A Lua se afasta da Terra cerca de 3,8 centímetros por ano.',
  'O corpo humano adulto tem 206 ossos.',
  'O Oceano Pacífico é maior do que todos os continentes juntos.',
  'As águas-vivas existem há mais de 500 milhões de anos.',
  'O guepardo vai de 0 a 100 km/h em cerca de 3 segundos.',
  'O pinguim-imperador consegue mergulhar a mais de 500 metros de profundidade.',
  'O Brasil é o maior produtor de café do mundo.',
  'O Pantanal é a maior planície alagável do planeta.',
  'As Cataratas do Iguaçu têm cerca de 275 quedas-d’água.',
  'O Sol concentra cerca de 99,8% de toda a massa do Sistema Solar.',
  'A luz do Sol leva cerca de 8 minutos para chegar à Terra.',
  'As unhas das mãos crescem mais rápido do que as dos pés.',
  'As impressões digitais do coala são muito parecidas com as humanas.',
  'A baleia-azul é o maior animal que já existiu na Terra.',
  'A língua da baleia-azul pode pesar tanto quanto um elefante.',
];

export const NOSTALGIA = [
  ['Fita K7 e a caneta para rebobinar', 'Quem nunca salvou a fita com uma caneta?'],
  ['Locadora de vídeo', '“Seja gentil, rebobine a fita antes de devolver.”'],
  ['Sessão da Tarde', 'Depois da escola, filme garantido na TV.'],
  ['Antena de TV com esponja de aço', 'Um ajuste aqui, outro ali… e a imagem voltava!'],
  ['Orelhão e cartão telefônico', 'E a coleção de cartões, quem tinha?'],
  ['Álbum de figurinhas da Copa', 'Trocar repetida no recreio era um evento.'],
  ['Internet discada', 'Aquele barulhinho da conexão… e só depois da meia-noite!'],
  ['Bate-papo e o “chamar atenção”', 'A janela tremia e todo mundo sabia quem era.'],
  ['Tamagotchi', 'O bichinho virtual que precisava de cuidado o dia inteiro.'],
  ['Celular tijolão e o jogo da cobrinha', 'A bateria durava uma semana!'],
  ['Mensagem de texto contando caracteres', 'Cada torpedo tinha que caber em 160 letras.'],
  ['Gravar música do rádio na fita', 'Torcendo para o locutor não falar por cima.'],
  ['Disquete', 'O ícone de “salvar” veio dele.'],
  ['Walkman', 'Música no bolso — e pilha de reserva na mochila.'],
  ['Discman', 'Andar devagarinho para o CD não pular.'],
  ['Máquina fotográfica de filme', '36 poses e a surpresa só na revelação.'],
  ['Caderno de perguntas', 'Nome, idade, cor preferida e “quem você ama?”'],
  ['Papel de carta', 'Colecionar, trocar… e nunca usar os mais bonitos.'],
  ['Mimeógrafo', 'O cheirinho da prova rodada na escola.'],
  ['Ioiô, pião e bolinha de gude', 'As brincadeiras que enchiam a rua.'],
  ['Tazos', 'Vinham no pacote de salgadinho e valiam ouro no recreio.'],
  ['Telefone de disco', 'Discar um número demorava — e ninguém reclamava.'],
  ['Agenda telefônica de papel', 'Os números importantes a gente sabia de cor.'],
  ['TV de tubo', 'Pesada, funda… e durava para sempre.'],
  ['Vinil na vitrola', 'Lado A, lado B e a capa como obra de arte.'],
  ['Guaraná em garrafa de vidro', 'E o casco retornável para trocar na venda.'],
  ['Brincar na rua até escurecer', 'Pique-esconde, amarelinha e pega-pega.'],
  ['Novela com a família reunida', 'Todo mundo na sala, na mesma hora.'],
];

// Ampliação F-96
CHARADAS.push(...MAIS_CHARADAS);
PIADAS.push(...MAIS_PIADAS);
MEMES.push(...MAIS_MEMES);
CURIOSIDADES.push(...MAIS_CURIOSIDADES);
NOSTALGIA.push(...MAIS_NOSTALGIA);
