/**
 * Charadas e piadas SOBRE MÍDIA (F-163) — conteúdo próprio, para toda a família e próprio para comércio (nada de política,
 * religião, preconceito, bebida ou palavrão). Cada item traz `foto`: termo de busca em inglês para a foto que combina com
 * o assunto (na charada, a foto da RESPOSTA — a pergunta sai desfocada para não entregar). Rodízio a cada 3 dias.
 */

/** { p: pista, r: resposta, foto } */
export const CHARADAS = [
  { p: 'Quanto mais se tira, maior fica?', r: 'O buraco', foto: 'deep hole in the ground' },
  { p: 'Tem dentes, mas não morde?', r: 'O pente', foto: 'hair comb' },
  { p: 'Cai em pé e corre deitada?', r: 'A chuva', foto: 'heavy rain falling' },
  { p: 'Tem cabeça e tem dente, não é bicho nem é gente?', r: 'O alho', foto: 'garlic cloves' },
  { p: 'Quanto mais seca, mais molhada fica?', r: 'A toalha', foto: 'bath towel' },
  { p: 'Passa diante do sol e não faz sombra?', r: 'O vento', foto: 'wind blowing field' },
  { p: 'Tem pescoço, mas não tem cabeça?', r: 'A garrafa', foto: 'glass bottle' },
  { p: 'Tem olho, mas não enxerga?', r: 'A agulha', foto: 'sewing needle and thread' },
  { p: 'Sobe quando a chuva desce?', r: 'O guarda-chuva', foto: 'umbrella in the rain' },
  { p: 'Tem coroa, mas não é rei; tem escamas, mas não é peixe?', r: 'O abacaxi', foto: 'pineapple' },
  { p: 'É seu, mas os outros usam muito mais do que você?', r: 'O seu nome', foto: 'name tag hello my name is' },
  { p: 'Tem asa, mas não voa; tem bico, mas não bica?', r: 'O bule', foto: 'teapot' },
  { p: 'Nasce grande e morre pequeno?', r: 'O lápis', foto: 'pencils sharpened' },
  { p: 'Tem cidades, mas não tem casas; tem rios, mas não tem água?', r: 'O mapa', foto: 'world map' },
  { p: 'Viaja o mundo inteiro sem sair do cantinho?', r: 'O selo', foto: 'postage stamps' },
  { p: 'Está no meio do começo, no começo do meio e no fim do fim?', r: 'A letra M', foto: 'alphabet letter blocks' },
  { p: 'Está sempre à sua frente, mas você nunca consegue ver?', r: 'O futuro', foto: 'road ahead horizon' },
  { p: 'Tem pernas, mas não anda?', r: 'A mesa', foto: 'wooden table' },
  { p: 'Dá muitas voltas e nunca sai do lugar?', r: 'O relógio', foto: 'wall clock' },
  { p: 'Tem boca, mas não fala; tem leito, mas não dorme?', r: 'O rio', foto: 'river landscape' },
  { p: 'Quanto mais se lava, mais suja fica?', r: 'A água', foto: 'dirty water in a bucket' },
  { p: 'Tem capa, mas não é super-herói; tem folhas, mas não é árvore?', r: 'O livro', foto: 'open book' },
  { p: 'Tem teclas, mas não abre nenhuma porta?', r: 'O piano', foto: 'piano keys' },
  { p: 'Tem casca, clara e gema, mas não é joia?', r: 'O ovo', foto: 'fresh eggs' },
  { p: 'Corre a casa inteira e depois fica de castigo no cantinho?', r: 'A vassoura', foto: 'broom' },
  { p: 'Tem barba, mas não é homem; tem dente, mas não é gente?', r: 'O milho', foto: 'corn on the cob' },
  { p: 'Quanto mais cresce, mais baixo fica?', r: 'O rabo do cavalo, quando penteado', foto: 'horse tail' },
  { p: 'Voa sem ter asas e chora sem ter olhos?', r: 'A nuvem', foto: 'dark rain cloud' },
  { p: 'Tem rabo, mas não é bicho; não tem asa, mas sabe voar?', r: 'A pipa', foto: 'kite flying in the sky' },
  { p: 'Anda sempre com a casa nas costas?', r: 'O caracol', foto: 'snail' },
  { p: 'É pequena como um rato e guarda a casa como um leão?', r: 'A chave', foto: 'house key' },
  { p: 'Dá um pulo e se veste de noiva?', r: 'A pipoca', foto: 'popcorn' },
  { p: 'Tem cabeça, mas não pensa; é riscado e pega fogo?', r: 'O fósforo', foto: 'matchstick flame' },
  { p: 'Entra na água e não se molha?', r: 'A sombra', foto: 'shadow on water' },
  { p: 'Quanto mais se enche, mais leve fica?', r: 'O balão', foto: 'colorful balloons' },
  { p: 'Sobe e desce, mas não sai do lugar?', r: 'A escada', foto: 'wooden staircase' },
  { p: 'É cheia de dedos, mas não tem unhas?', r: 'A luva', foto: 'winter gloves' },
  { p: 'Tem bolsa na barriga e anda aos pulos?', r: 'O canguru', foto: 'kangaroo' },
  { p: 'Mora no mar e tem oito braços?', r: 'O polvo', foto: 'octopus' },
  { p: 'É duro por fora, branco por dentro e tem água?', r: 'O coco', foto: 'coconut' },
  { p: 'É verde, mas não é planta; fala, mas não é gente?', r: 'O papagaio', foto: 'green parrot' },
  { p: 'É doce, é gelado e derrete no sol?', r: 'O sorvete', foto: 'ice cream cone' },
  { p: 'Tem dentes e come madeira?', r: 'O serrote', foto: 'hand saw wood' },
  { p: 'Tem chapéu e um pé só?', r: 'O cogumelo', foto: 'mushroom' },
  { p: 'Quando a gente corta, quem chora é a gente?', r: 'A cebola', foto: 'onion' },
  { p: 'Tem asas de metal e leva gente pelo céu?', r: 'O avião', foto: 'airplane in the sky' },
  { p: 'Tem duas rodas e pedais e anda com a força das pernas?', r: 'A bicicleta', foto: 'bicycle' },
  { p: 'É preto e branco e parece um cavalo de pijama?', r: 'A zebra', foto: 'zebra' },
  { p: 'Todo mundo tem, todo mundo gasta, mas ninguém consegue guardar?', r: 'O tempo', foto: 'hourglass sand' },
  { p: 'Quanto mais você dá, mais você tem?', r: 'O sorriso', foto: 'happy smiling person' },
  { p: 'Dorme de dia de cabeça para baixo e voa de noite?', r: 'O morcego', foto: 'bat' },
  { p: 'Tem pescoço comprido e come as folhas lá do alto?', r: 'A girafa', foto: 'giraffe' },
  { p: 'É redonda, pula e vive nos pés dos jogadores?', r: 'A bola', foto: 'soccer ball on grass' },
  { p: 'Tem cartas, mas não é carteiro?', r: 'O baralho', foto: 'deck of playing cards' },
  { p: 'Fica na parede e marca os dias do ano?', r: 'O calendário', foto: 'wall calendar' },
  { p: 'Tem pontas, mas não fura; brilha no céu à noite?', r: 'A estrela', foto: 'stars night sky' },
  { p: 'Muda de forma todo mês, mas é sempre a mesma?', r: 'A lua', foto: 'full moon' },
  { p: 'Cai do céu, é branquinha e gelada?', r: 'A neve', foto: 'snowfall' },
  { p: 'Aparece depois da chuva e tem sete cores?', r: 'O arco-íris', foto: 'rainbow' },
  { p: 'Toca sem ter mãos e avisa que tem gente na porta?', r: 'A campainha', foto: 'door bell' },
  { p: 'Não tem pé nem mão, mas sobe pelo telhado?', r: 'A fumaça', foto: 'smoke chimney' },
  { p: 'Fala todas as línguas, mas nunca aprendeu nenhuma?', r: 'O eco', foto: 'mountain valley shouting' },
  { p: 'Tem cauda longa e brilhante e cruza o céu?', r: 'O cometa', foto: 'comet night sky' },
  { p: 'Fica cheio de dia e vazio de noite, e você calça?', r: 'O sapato', foto: 'pair of shoes' },
  { p: 'Tem cabeça de ferro, cabo de madeira e vive batendo?', r: 'O martelo', foto: 'hammer' },
  { p: 'Vive molhada, mas nunca pega chuva?', r: 'A língua', foto: 'tongue out funny' },
  { p: 'Fica de boca aberta o dia inteiro esperando cartas?', r: 'A caixa de correio', foto: 'mailbox' },
  { p: 'Anda na água e se move com a força do vento?', r: 'O barco a vela', foto: 'sailboat' },
  { p: 'Tem oito patas e tece a própria casa?', r: 'A aranha', foto: 'spider web' },
  { p: 'Canta de manhãzinha e acorda a fazenda inteira?', r: 'O galo', foto: 'rooster' },
  { p: 'Tem espinhos, mas dá uma flor perfumada?', r: 'A rosa', foto: 'red rose' },
  { p: 'É verde por fora, vermelha por dentro e cheia de sementes?', r: 'A melancia', foto: 'watermelon slice' },
  { p: 'É amarela, alongada e o macaco adora?', r: 'A banana', foto: 'bananas' },
  { p: 'Tem bigodes, mia e adora caçar rato?', r: 'O gato', foto: 'cat portrait' },
  { p: 'Late, abana o rabo e é o melhor amigo do homem?', r: 'O cachorro', foto: 'happy dog' },
  { p: 'Fica na torre da igreja e badala as horas?', r: 'O sino', foto: 'church bell tower' },
  { p: 'Tem janelas, leva muita gente pela cidade e para em todo ponto?', r: 'O ônibus', foto: 'city bus' },
  { p: 'Tem trilhos, vagões e apita na estação?', r: 'O trem', foto: 'train on tracks' },
  { p: 'É gelada, tem porta e guarda a comida?', r: 'A geladeira', foto: 'open refrigerator' },
  { p: 'Esquenta a comida sem fogo, em poucos minutos?', r: 'O micro-ondas', foto: 'microwave oven kitchen' },
  { p: 'Tem cordas, mas não é varal; faz música quando toca?', r: 'O violão', foto: 'acoustic guitar' },
  { p: 'Tem hélices, gira sem sair do lugar e refresca a casa?', r: 'O ventilador', foto: 'electric fan' },
  { p: 'Tem areia, mas não é praia; marca o tempo virando?', r: 'A ampulheta', foto: 'hourglass' },
  { p: 'Tem agulha, mas não costura; aponta sempre para o norte?', r: 'A bússola', foto: 'compass' },
  { p: 'Tem lente e deixa tudo maior?', r: 'A lupa', foto: 'magnifying glass' },
  { p: 'É verde, pula e faz “croac”?', r: 'O sapo', foto: 'green frog' },
  { p: 'Tem tromba, orelhas grandes e é o maior animal da terra?', r: 'O elefante', foto: 'elephant' },
  { p: 'Tem listras, é da família do gato e vive na floresta?', r: 'O tigre', foto: 'tiger' },
  // pegadinhas: a graça está na resposta que ninguém espera
  { p: 'Qual é o animal que anda com as patas?', r: 'Todos eles!', foto: 'animals walking together' },
  { p: 'Qual mês do ano tem 28 dias?', r: 'Todos eles!', foto: 'calendar months' },
  { p: 'Pesa mais: 1 kg de algodão ou 1 kg de ferro?', r: 'Os dois pesam 1 kg!', foto: 'weighing scale' },
  { p: 'Qual palavra está escrita errado em todo dicionário?', r: 'A palavra “errado”', foto: 'dictionary open' },
  { p: 'O que o carteiro faz quando chega ao fim da rua?', r: 'Vira a esquina e continua entregando!', foto: 'mail carrier delivering letters' },
  { p: 'Tem quatro pernas de manhã, duas ao meio-dia e três à noite?', r: 'O ser humano: engatinha, anda e usa bengala', foto: 'baby crawling' },
  { p: 'Chega sempre antes do dinheiro e ninguém o convida?', r: 'O boleto', foto: 'bills and calculator' },
  { p: 'Eu sou leve como uma pena, mas nem o homem mais forte me segura por mais de cinco minutos?', r: 'A respiração', foto: 'deep breath outdoors' },
];

/** { p: pergunta, r: resposta, foto } */
export const PIADAS = [
  { p: 'Por que o livro de matemática ficou triste?', r: 'Porque tinha muitos problemas.', foto: 'math textbook equations' },
  { p: 'O que o zero disse para o oito?', r: 'Que cinto bonito!', foto: 'number eight' },
  { p: 'Qual é o doce preferido do átomo?', r: 'Pé-de-molécula.', foto: 'candy sweets' },
  { p: 'Como o elétron atende o telefone?', r: 'Próton!', foto: 'old telephone' },
  { p: 'O que a vaca foi fazer no espaço?', r: 'Procurar a Via Láctea.', foto: 'cow in a field' },
  { p: 'Qual é o animal mais antigo?', r: 'A zebra, porque é em preto e branco.', foto: 'zebra black and white' },
  { p: 'O que o tomate foi fazer no banco?', r: 'Tirar extrato.', foto: 'ripe red tomatoes' },
  { p: 'Qual é a fruta que anda de trem?', r: 'O kiwiuiuiui!', foto: 'kiwi fruit' },
  { p: 'O que o cavalo foi fazer no orelhão?', r: 'Passar um trote.', foto: 'horse galloping' },
  { p: 'O que o café disse para o açúcar?', r: 'Sem você, a minha vida é amarga.', foto: 'coffee cup and sugar' },
  { p: 'Qual é o peixe que caiu do décimo andar?', r: 'Aaaaaaatum!', foto: 'tuna fish' },
  { p: 'Por que o computador foi preso?', r: 'Porque executou um programa!', foto: 'laptop computer' },
  { p: 'O que o lápis disse para o apontador?', r: 'Deixa de rodeio e vai direto ao ponto.', foto: 'pencil sharpener' },
  { p: 'Qual é a cidade brasileira que não tem táxi?', r: 'Uberlândia.', foto: 'taxi city street' },
  { p: 'O que o pato disse para a pata?', r: 'Vem quá!', foto: 'ducks on a lake' },
  { p: 'Por que o celular foi ao psicólogo?', r: 'Porque perdeu o contato com a realidade.', foto: 'smartphone' },
  { p: 'O que um ponteiro do relógio disse para o outro?', r: 'Nos vemos daqui a uma hora!', foto: 'clock hands' },
  { p: 'Qual é a comida preferida do Wi-Fi?', r: 'Rede-limão.', foto: 'wifi router' },
  { p: 'Por que o elefante não pega fogo?', r: 'Porque ele já nasceu cinza.', foto: 'elephant' },
  { p: 'Por que o fantasma não mente?', r: 'Porque dá para ver através dele.', foto: 'ghost costume' },
  { p: 'O que a esfera disse para o cubo?', r: 'Deixa de ser quadrado!', foto: 'sphere and cube' },
  { p: 'O que o cadarço disse para o tênis?', r: 'Estou amarrado em você!', foto: 'sneakers shoelaces' },
  { p: 'O que o mar disse para a praia?', r: 'Nada, só deu uma onda.', foto: 'ocean wave beach' },
  { p: 'Qual é o animal que não vale mais nada?', r: 'O javali.', foto: 'wild boar' },
  { p: 'Por que o jacaré tirou o filho da escola?', r: 'Porque ele réptil de ano.', foto: 'alligator' },
  { p: 'Qual é o café mais perigoso do mundo?', r: 'O ex-presso.', foto: 'espresso coffee' },
  { p: 'Por que o menino jogou o relógio pela janela?', r: 'Para ver o tempo voar.', foto: 'alarm clock' },
  { p: 'Por que a professora usava óculos escuros?', r: 'Porque os alunos eram brilhantes.', foto: 'teacher classroom' },
  { p: 'O que o peixe faz no computador?', r: 'Navega na internet.', foto: 'fish aquarium' },
  { p: 'Qual é a comida que liga e desliga?', r: 'O strogonoff.', foto: 'stroganoff dish' },
  { p: 'O que o martelo disse para o prego?', r: 'Você é muito cabeça-dura!', foto: 'hammer and nails' },
  { p: 'O que o açúcar disse para a água?', r: 'Com você eu me derreto todo.', foto: 'sugar cubes' },
  { p: 'Por que a vaca usa sino?', r: 'Porque a buzina não funciona.', foto: 'cow with bell' },
  { p: 'O que o ovo disse para a frigideira?', r: 'Você me deixa frito!', foto: 'fried eggs pan' },
  { p: 'Por que o livro foi ao médico?', r: 'Porque estava com dor na lombada.', foto: 'books on a shelf' },
  { p: 'O que o nariz disse para os óculos?', r: 'Pode se apoiar em mim!', foto: 'eyeglasses' },
  { p: 'O que o celular disse para o carregador?', r: 'Sem você eu fico sem energia.', foto: 'phone charger' },
  { p: 'O que um tijolo disse para o outro?', r: 'Tem um ciumento entre nós.', foto: 'brick wall' },
  { p: 'Por que o gato não gosta de computador?', r: 'Porque tem medo do mouse.', foto: 'cat and computer mouse' },
  { p: 'O que o limão disse para o açúcar?', r: 'Juntos a gente vira uma limonada!', foto: 'lemonade' },
  { p: 'Qual é a fruta mais paciente?', r: 'A pera, porque sabe esperar.', foto: 'pears' },
  { p: 'O que o chiclete disse para o sapato?', r: 'Estou grudado em você!', foto: 'bubble gum' },
  { p: 'Por que a planta foi ao dentista?', r: 'Para tratar a raiz.', foto: 'potted plant' },
  { p: 'Qual é o animal que vive de terno?', r: 'O pinguim.', foto: 'penguin' },
  { p: 'Por que o músico levou uma escada para o show?', r: 'Para alcançar as notas mais altas.', foto: 'musician on stage' },
  { p: 'O que o feijão disse para o arroz?', r: 'Juntos somos o prato preferido do Brasil!', foto: 'rice and beans plate' },
  { p: 'O que o guarda-chuva disse para a chuva?', r: 'Pode cair que eu te seguro!', foto: 'umbrella rain street' },
  { p: 'Por que o computador foi ao médico?', r: 'Porque estava com vírus.', foto: 'sick laptop' },
  { p: 'O que a caneta disse para o caderno?', r: 'Com você a minha história fica escrita!', foto: 'pen and notebook' },
  // novas
  { p: 'O que o gato faz quando está com sede?', r: 'Mia água!', foto: 'cat drinking water' },
  { p: 'Qual é o cúmulo da rapidez?', r: 'Apagar a luz e chegar na cama antes de escurecer.', foto: 'light switch bedroom' },
  { p: 'O que o sorvete disse para o sol?', r: 'Não me olha assim que eu derreto!', foto: 'melting ice cream' },
  { p: 'O que a pipoca disse para o milho?', r: 'Estou estourando de felicidade!', foto: 'popcorn bowl' },
  { p: 'Por que o ventilador é tão popular?', r: 'Porque tem muitos fãs!', foto: 'electric fan' },
  { p: 'O que a bola disse para o jogador?', r: 'Não me chuta, me trata bem!', foto: 'soccer player ball' },
  { p: 'O que o chocolate disse para o sorvete?', r: 'Juntos a gente vira a melhor sobremesa!', foto: 'chocolate ice cream' },
  { p: 'Por que a lanterna foi promovida?', r: 'Porque era muito brilhante.', foto: 'flashlight in the dark' },
  { p: 'Qual é a bebida preferida do fantasma?', r: 'Suco de BOO-ranja!', foto: 'orange juice glass' },
  { p: 'O que o cabelo disse para o secador?', r: 'Você me deixa de cabeça quente!', foto: 'hair dryer' },
  { p: 'Por que o astronauta não paga aluguel?', r: 'Porque já mora no mundo da Lua.', foto: 'astronaut' },
  { p: 'O que o cinto disse para a calça?', r: 'Fica tranquila, eu te seguro!', foto: 'leather belt' },
  { p: 'O que a vela disse para o bolo?', r: 'Eu me apago, mas a festa continua!', foto: 'birthday cake candles' },
  { p: 'Por que o professor de inglês é tão calmo?', r: 'Porque sempre diz “take it easy”!', foto: 'english teacher whiteboard' },
  { p: 'O que o espelho disse para a pessoa?', r: 'Eu só mostro o que você me mostra!', foto: 'mirror reflection' },
  { p: 'Por que o caderno sempre tem razão?', r: 'Porque tudo que ele diz está escrito!', foto: 'notebook writing' },
  { p: 'O que o sol disse para a lua?', r: 'Tão grande e ainda não te deixam sair de dia!', foto: 'sun and moon sky' },
  { p: 'O que a impressora disse para a outra?', r: 'Essa folha é sua ou é impressão minha?', foto: 'office printer paper' },
  { p: 'Por que o esqueleto não foi à festa?', r: 'Porque não tinha ninguém para ir com ele.', foto: 'skeleton decoration' },
  { p: 'Qual é o contrário de volátil?', r: 'Vem cá, sobrinho.', foto: 'uncle and nephew' },
  { p: 'O que é um pontinho amarelo no céu?', r: 'Um yellowcóptero.', foto: 'yellow helicopter' },
  { p: 'Qual é o rei dos queijos?', r: 'O reiqueijão.', foto: 'cheese board' },
  { p: 'Por que a galinha atravessou a rua?', r: 'Para chegar do outro lado.', foto: 'chicken crossing the road' },
  { p: 'Por que o pinguim não usa celular?', r: 'Porque já vive no Polo… e sem sinal!', foto: 'penguin on ice' },
  { p: 'Por que o eletricista nunca fica nervoso?', r: 'Porque ele sabe que tudo é uma questão de corrente.', foto: 'electrician working' },
  { p: 'Por que a internet parece um buffet?', r: 'Porque tem de tudo, mas você sempre volta para a mesma coisa.', foto: 'buffet food' },
  { p: 'O que o mágico disse para a cartola?', r: 'Vê se não esconde o coelho de novo!', foto: 'magician top hat' },
];
