// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

import { supabaseConfig } from '../../supabaseConfig';

if (!supabaseConfig.url || !supabaseConfig.key) {
  throw new Error("⚠️ Supabase credentials missing. Zero Mock Protocol: system cannot initialize without valid credentials.");
}

export const supabase = createClient<Database>(supabaseConfig.url, supabaseConfig.key, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});