// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const getStoredConfig = () => {
  const storedUrl = localStorage.getItem('VITE_SUPABASE_URL');
  const storedKey = localStorage.getItem('VITE_SUPABASE_PUBLISHABLE_KEY');
  return {
    url: storedUrl || import.meta.env.VITE_SUPABASE_URL,
    key: storedKey || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY
  };
};

// Safe Initialization
let supabaseInstance;

try {
  if (!supabaseConfig.url || !supabaseConfig.key) {
    console.warn("⚠️ Supabase credentials missing. Initializing Fallback Client (Offline Mode).");
    // Return a dummy client that doesn't crash but logs errors on usage
    supabaseInstance = {
      from: () => ({
        select: () => Promise.resolve({ data: null, error: { message: "Missing Credentials" } }),
        insert: () => Promise.resolve({ data: null, error: { message: "Missing Credentials" } }),
        update: () => Promise.resolve({ data: null, error: { message: "Missing Credentials" } }),
        delete: () => Promise.resolve({ data: null, error: { message: "Missing Credentials" } }),
        on: () => ({ subscribe: () => { } }),
      }),
      auth: {
        getSession: () => Promise.resolve({ data: { session: null }, error: null }),
        onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => { } } } }),
      },
      channel: () => ({
        on: () => ({ subscribe: () => { } }),
        subscribe: () => { }
      })
    } as any;
  } else {
    supabaseInstance = createClient<Database>(supabaseConfig.url, supabaseConfig.key, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    });
  }
} catch (e) {
  console.error("Critical Error initializing Supabase:", e);
  supabaseInstance = {} as any;
}

export const supabase = supabaseInstance;